### ISSUE TITLE
There is no undefined in JSON, only null, according to http://www.json.org/

### ISSUE THREAD

**Issue by Artoria2e5** [JKSN-format/JKSN#1]
<_<

**Comment by m13253** [comment]
Yes it is. There is no big integer in JSON either (JSON only garantees 48-bit precision of numbers).

Therefore, JKSN is single-direction compatible to JSON: every valid JSON stream can be transliterated in JKSN, not the reverse direction.

**Comment by Artoria2e5** [comment]
Sounds like WTF-8 and UTF-8. I like this idea. (hug (???

**Comment by m13253** [comment]
Yes, it's true.
